package PrimeApp;


/**
* PrimeApp/PrimeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Prime.idl
* Sunday, 10 May, 2026 3:51:55 PM IST
*/

public interface PrimeOperations 
{
  String checkPrime (int num);
} // interface PrimeOperations
