package PrimeApp;


/**
* PrimeApp/Prime.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Prime.idl
* Sunday, 10 May, 2026 3:51:55 PM IST
*/

public interface Prime extends PrimeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Prime
