package CalculatorApp;


/**
* CalculatorApp/Calculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Saturday, 9 May, 2026 9:56:57 PM IST
*/

public interface Calculator extends CalculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculator
