package OddEvenApp;


/**
* OddEvenApp/OddEvenPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OddEven.idl
* Sunday, 10 May, 2026 3:40:58 PM IST
*/

public abstract class OddEvenPOA extends org.omg.PortableServer.Servant
 implements OddEvenApp.OddEvenOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("checkNumber", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // OddEvenApp/OddEven/checkNumber
       {
         int num = in.read_long ();
         String $result = null;
         $result = this.checkNumber (num);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:OddEvenApp/OddEven:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public OddEven _this() 
  {
    return OddEvenHelper.narrow(
    super._this_object());
  }

  public OddEven _this(org.omg.CORBA.ORB orb) 
  {
    return OddEvenHelper.narrow(
    super._this_object(orb));
  }


} // class OddEvenPOA
