package OddEvenApp;


/**
* OddEvenApp/OddEvenHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OddEven.idl
* Sunday, 10 May, 2026 3:40:58 PM IST
*/

abstract public class OddEvenHelper
{
  private static String  _id = "IDL:OddEvenApp/OddEven:1.0";

  public static void insert (org.omg.CORBA.Any a, OddEvenApp.OddEven that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static OddEvenApp.OddEven extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (OddEvenApp.OddEvenHelper.id (), "OddEven");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static OddEvenApp.OddEven read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_OddEvenStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, OddEvenApp.OddEven value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static OddEvenApp.OddEven narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OddEvenApp.OddEven)
      return (OddEvenApp.OddEven)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OddEvenApp._OddEvenStub stub = new OddEvenApp._OddEvenStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static OddEvenApp.OddEven unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OddEvenApp.OddEven)
      return (OddEvenApp.OddEven)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OddEvenApp._OddEvenStub stub = new OddEvenApp._OddEvenStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
