package OddEvenApp;

/**
* OddEvenApp/OddEvenHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OddEven.idl
* Sunday, 10 May, 2026 3:40:58 PM IST
*/

public final class OddEvenHolder implements org.omg.CORBA.portable.Streamable
{
  public OddEvenApp.OddEven value = null;

  public OddEvenHolder ()
  {
  }

  public OddEvenHolder (OddEvenApp.OddEven initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OddEvenApp.OddEvenHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OddEvenApp.OddEvenHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OddEvenApp.OddEvenHelper.type ();
  }

}
