package OddEvenApp;


/**
* OddEvenApp/OddEvenOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OddEven.idl
* Sunday, 10 May, 2026 3:40:58 PM IST
*/

public interface OddEvenOperations 
{
  String checkNumber (int num);
} // interface OddEvenOperations
