package StringApp;


/**
* StringApp/StringOperation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringOperation.idl
* Sunday, 10 May, 2026 3:27:16 PM IST
*/

public interface StringOperation extends StringOperationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StringOperation
