package StringApp;


/**
* StringApp/StringOperationPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringOperation.idl
* Sunday, 10 May, 2026 3:27:16 PM IST
*/

public abstract class StringOperationPOA extends org.omg.PortableServer.Servant
 implements StringApp.StringOperationOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("length", new java.lang.Integer (0));
    _methods.put ("reverse", new java.lang.Integer (1));
    _methods.put ("uppercase", new java.lang.Integer (2));
    _methods.put ("lowercase", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // StringApp/StringOperation/length
       {
         String str = in.read_string ();
         int $result = (int)0;
         $result = this.length (str);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // StringApp/StringOperation/reverse
       {
         String str = in.read_string ();
         String $result = null;
         $result = this.reverse (str);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // StringApp/StringOperation/uppercase
       {
         String str = in.read_string ();
         String $result = null;
         $result = this.uppercase (str);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // StringApp/StringOperation/lowercase
       {
         String str = in.read_string ();
         String $result = null;
         $result = this.lowercase (str);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:StringApp/StringOperation:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public StringOperation _this() 
  {
    return StringOperationHelper.narrow(
    super._this_object());
  }

  public StringOperation _this(org.omg.CORBA.ORB orb) 
  {
    return StringOperationHelper.narrow(
    super._this_object(orb));
  }


} // class StringOperationPOA
