package StringApp;


/**
* StringApp/StringOperationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringOperation.idl
* Sunday, 10 May, 2026 3:27:16 PM IST
*/

public interface StringOperationOperations 
{
  int length (String str);
  String reverse (String str);
  String uppercase (String str);
  String lowercase (String str);
} // interface StringOperationOperations
